name: Data QA
#check if headers have changed day to day

on: 
  schedule:
   #run daily at 7UTC
    - cron: '0 7 * * *'
# on:
#   push:
#    branches: [ master ]

jobs:
 qa:   
    name: Data QA
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-user@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest-xml-reporting
    - name: pull 
      run: |
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
    - name: ca-gov
      run: python tests/csvTest.py ./data/ca/gov/cases/raw 1
      if: always()   
    - name: ny-doh
      run: python tests/csvTest.py ./data/us-ny/ny-doh/raw 1
      if: always()  
    - name: oh-doh
      run: python tests/csvTest.py ./data/us-oh/oh-doh/raw 1
      if: always() 
#     - name: tn-doh
#       run: |
#         python tests/csvTest.py ./data/us-tn/tn-doh/age/raw 1
#         python tests/csvTest.py ./data/us-tn/tn-doh/county_new/raw 1
#         python tests/csvTest.py ./data/us-tn/tn-doh/daily_case_info/raw 1
#         python tests/csvTest.py ./data/us-tn/tn-doh/race_eth_sex/raw 1
#       if: always() 
      #these are now monitored by the db monitor instead
#     - name: co-knox
#       run: |
#        python tests/csvTest.py ./data/us-tn/co-knox/covid_age/raw 1
#        python tests/csvTest.py ./data/us-tn/co-knox/covid_bed_capacity/raw 1
#        python tests/csvTest.py ./data/us-tn/co-knox/covid_cases/raw 1
#        python tests/csvTest.py ./data/us-tn/co-knox/covid_gender/raw 1
#       if: always() 
    - name: Slack notification
      #should run if any previous step fails
      if: failure()
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_USERNAME: GitHub Actions # Optional. (defaults to webhook app)
       SLACK_CHANNEL: alerts-rds # Optional. (defaults to webhook)
       SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses: Ilshidur/action-slack@master
      with:
          args: 'Something went wrong in the QA workflow.' # Optional

      
