name: TN DOH Data

on: workflow_dispatch
#    schedule:
#    #run daily at 5:10 UTC
#      - cron: '10 5 * * *'


jobs:
 tn-doh:   
    name: TN-DOH Data Ingestion
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-user@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install addfips
        pip install xlsx2csv
    - name: pull data via curl
      run: |
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       /bin/sh scripts/xlsxDownload.sh TN-AGE https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-Age.XLSX data/us-tn/tn-doh/age/raw
       /bin/sh scripts/xlsxDownload.sh TN-COUNTY-NEW https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-County-New.XLSX data/us-tn/tn-doh/county_new/raw
       /bin/sh scripts/xlsxDownload.sh TN-CASE-INFO https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-Daily-Case-Info.XLSX data/us-tn/tn-doh/daily_case_info/raw
       /bin/sh scripts/xlsxDownload.sh TN-RACE https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-RaceEthSex.XLSX data/us-tn/tn-doh/race_eth_sex/raw

    - name: transform
      run: |
       python data/us-tn/tn-doh/harvester.py
       git pull github ${GITHUB_REF} --ff-only
       git add .
       git commit -m "adding TN data via github actions"
       git push github HEAD:${GITHUB_REF}
    - name: Slack notification
      #should run if any previous step fails
      if: failure()
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_USERNAME: GitHub Actions # Optional. (defaults to webhook app)
       SLACK_CHANNEL: alerts-rds # Optional. (defaults to webhook)
       SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses: Ilshidur/action-slack@master
      with:
          args: 'Something went wrong in the Tennesee workflow.' # Optional
